# Generated by Django 2.1.5 on 2019-03-15 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='login',
            new_name='email',
        ),
    ]
