# Generated by Django 2.1.5 on 2019-02-21 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0002_auto_20190218_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinorder',
            name='priceProduct',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True),
        ),
    ]
