# Generated by Django 2.1.5 on 2019-02-26 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0004_productincart'),
    ]

    operations = [
        migrations.AddField(
            model_name='productincart',
            name='sessionKey',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
