# Generated by Django 2.1.5 on 2019-02-27 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0005_productincart_sessionkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='allSume',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='productincart',
            name='priceProduct',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='productincart',
            name='totalPrice',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='productinorder',
            name='priceProduct',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='productinorder',
            name='totalPrice',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
