# Generated by Django 2.1.5 on 2019-02-17 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hits',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='news',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sale',
            field=models.BooleanField(default=False),
        ),
    ]
