# Generated by Django 2.1.5 on 2019-02-22 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_product_isactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageforproduct',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='imageforproduct',
            name='isMain',
            field=models.BooleanField(default=False),
        ),
    ]
