# Generated by Django 2.1.5 on 2019-03-11 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0009_auto_20190227_1508'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productmark',
            options={'verbose_name': 'Марка', 'verbose_name_plural': 'Марки'},
        ),
    ]
